### ISSUE TITLE
I need some help

### ISSUE THREAD

**Issue by RashidAlsuwaidi** [oreparaz/dudect#10]
i have been trying to compile the test code but i keep getting an error message "undefined symbols for architecture x86_64: "_main", referenced from: implicit entry/start for main executable ld: symbol(s) not found for architecture x86_64 clang: error: linker command failed with exit code 1 (use -v to see invocation) " I'm using xcode to compile the code .

**Comment by oreparaz** [comment]
Hope you sorted it out
